on: [push]

jobs:
  test-action:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Creating and uploading Test SBOM.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate unique version file (to avoid conflicts with other runs)
        run: |
          echo "${{ matrix.os }}-${{ github.run_id }}" > ./unique_version.txt
          echo "Generated version:"
          cat ./unique_version.txt
        shell: bash

      - name: Creating SBOM
        uses: anchore/sbom-action@v0
        with:
          file: './test_project/Cargo.lock'
          output-file: './sbom.cdx.json'
          format: 'cyclonedx-json'
          upload-artifact: 'false'

      - name: Setting up BOMnipotent Client
        id: setup-latest
        uses: Weichwerke-Heidrich-Software/setup-bomnipotent-action@v1
        with:
          domain: 'https://bomnipotent.wwh-soft.com'
          user: 'wwh_soft_robot'
          secret-key: ${{ secrets.CLIENT_SECRET_KEY }}
          log-level: 'debug'

      - name: Uploading SBOM
        uses: Weichwerke-Heidrich-Software/upload-bom-action@v0
        with:
          bom: './sbom.cdx.json'
          name: '${{ github.event.repository.name }}-test-project'
          version: './unique_version.txt'
          tlp: 'white'
          on-existing: 'replace' # Mainly to catch the case where a previous test run failed mid-way.

      - name: Trying to upload same SBOM again
        uses: Weichwerke-Heidrich-Software/upload-bom-action@v0
        with:
          bom: './sbom.cdx.json'
          name: '${{ github.event.repository.name }}-test-project'
          version: './unique_version.txt'
          tlp: 'white'
          on-existing: 'skip'

      - name: Replacing SBOM
        uses: Weichwerke-Heidrich-Software/upload-bom-action@v0
        with:
          bom: './test_project/static_bom.cdx.json' # Checked into this repo.
          name: '${{ github.event.repository.name }}-test-project'
          version: './unique_version.txt'
          tlp: 'white'
          on-existing: 'replace'

      - name: Cleanup (delete freshly uploaded SBOM)
        run: |
          bomnipotent_client bom delete '${{ github.event.repository.name }}-test-project' "$(cat ./unique_version.txt)"
        shell: bash
